os: Visual Studio 2015
environment:
  VisualStudioVersion: 14.0
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(appveyor_repo_commit)"
before_build:
  - nuget restore
build:
  project: Elmah.DynamoDB.sln
  publish_nuget: true
  publish_nuget_symbols: true
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: false
  artifact: /.*\.nupkg/