
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
  - dotnet --version
  - where dotnet
  - dotnet restore
build: off
build_script:
  - dotnet pack src/Elmah.DynamoDB --include-symbols --configuration Release --output artifacts
test: off
artifacts:
  - path: 'src\**\*.nupkg'
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: znBJ3DWOhYRo43eFKnVGodpP2p7fw1Lpdqf27D2SJ61FJemoGQHiAGgZBEmwjVLE
  skip_symbols: false
  artifact: /.*\.nupkg/
